### PR TITLE
GUACAMOLE-2 Added Missing translations for screen recording etc in Dutch

### PR DESCRIPTION
**Pull request by nrbrt**
I added the missing translations from the en.json file and made a style correction.

### CODE REVIEW

**Comment by mike-jumper** [comment]
Looks pretty good. Can you update the commit message to specify the JIRA issue?

ie:

> GUACAMOLE-2: Added Missing translations for screen recording, etc. in Dutch.

**Comment by nrbrt** [comment]
sure, do you mean by following [this guide](https://help.github.com/articles/changing-a-commit-message/)
 and force pushing?  Do I need to do a new pull request afterwards?

**Comment by mike-jumper** [comment]
Just amend the commit and force push no problem

**Comment by nrbrt** [comment]
done

**Pull request merged**
