### PR TITLE
GUACAMOLE-332: Correct appearance of CAS redirect notification.

### PR DESCRIPTION
**Pull request by mike-jumper**
This change modifies the CAS extension to use a template for the contents of its ticket field, displaying a "please wait" notification. The build has been modified to pre-cache the field template and minify all associated CSS and JS.

### CODE REVIEW

**Comment by necouchman** [comment]
Without having tested it, changes look okay to me.

**Comment by necouchman** [comment]
Oh, crud...I just messed this one up and merged into upstream master instead of staging/0.9.13-incubating.  Anything that can be done about that?

:no_good_man:

**Comment by mike-jumper** [comment]
You'll just need to merge to staging/0.9.13-incubating as normal, and then
merge staging back to master.

I also have an experimental git pre-push hook that you might want to try -
it verifies the PR merge base against the push destination prior to
allowing the push.

**Comment by necouchman** [comment]
Okay, merged it to staging, now just need to merge staging to master.  Is this going to require a force?  Or create duplicate entries?

**Comment by mike-jumper** [comment]
On Jun 27, 2017 11:59, "necouchman" <notifications@github.com> wrote:

Okay, merged it to staging, now just need to merge staging to master. Is
this going to require a force?


No - never ever ever force push to the main repos.

Or create duplicate entries?


Yep.

**Comment by necouchman** [comment]
Okay, I've merged the changes over to staging/0.9.13-incubating, then pushed that back onto master.  Sorry about that.  I would definitely be interested in the pre-push hook you have...

**Comment by mike-jumper** [comment]
Here you go: https://gist.github.com/mike-jumper/5f687b1e4e08eff19b7d90bee4184ec5

**Pull request merged**
